VHernandezCocteleria/Models/ErrorViewModel.cs
namespace VHernandezCocteleria.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VHernandezCocteleria/Controllers/CoctelesController.cs
using Microsoft.AspNetCore.Mvc;
using ML;
using Newtonsoft.Json;

namespace VHernandezCocteleria.Controllers
{
    public class CoctelesController : Controller
    {
        //public IActionResult GetAllNombre()
        //{
        //    ML.Cocteles cocteles = new ML.Cocteles();
        //    cocteles.Coctels = new List<object>();
        //    using (var client = new HttpClient())
        //    {
        //        client.BaseAddress = new Uri("https://www.thecocktaildb.com/api/");
        //        var responsetask = client.GetAsync("json/v1/1/search.php?f=a");
        //        responsetask.Wait();
        //        var result = responsetask.Result;
        //        if (result.IsSuccessStatusCode)
        //        {
        //            var readTask = result.Content.ReadAsStringAsync();
        //            readTask.Wait();

        //            foreach (var resultItem in readTask.Result.ToArray())
        //            {
        //                ML.Cocteles resultitemlist = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Cocteles>(resultItem.ToString());
        //                cocteles.Coctels.Add(resultitemlist);
        //            }
        //        }
        //    }
        //        return View(cocteles);
        //}

        
        public IActionResult GetAllNombre() 
        {
            ML.drinks cocteles = new ML.drinks();
            cocteles.Coctels = new List<object>();
            using(var client =new HttpClient())
            {
                client.BaseAddress = new Uri("https://www.thecocktaildb.com/api/");
                var responsetask = client.GetAsync("json/v1/1/search.php?f=a"); 
                responsetask.Wait();
                var result = responsetask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readtask = result.Content.ReadAsAsync<dynamic>();
                    readtask.Wait();
                    foreach (dynamic item in readtask.Result.drinks)
                    {
                        ML.drinks resultitem = new ML.drinks();
                        resultitem.idDrink = item.idDrink;
                        resultitem.strDrink = item.strDrink;
                        resultitem.strDrinkThumb = item.strDrinkThumb;
                        resultitem.strInstructions = item.strInstructionsES;
                        resultitem.strCategory = item.strCategory;
                        resultitem.strIngredient1 = item.strIngredient1;
                        resultitem.strIngredient2 = item.strIngredient2;
                        resultitem.strIngredient3 = item.strIngredient3;
                        resultitem.strIngredient4 = item.strIngredient4;
                        resultitem.Imagen1 = "https://www.thecocktaildb.com/images/ingredients/" + resultitem.strIngredient1 + "-small.png";
                        resultitem.Imagen2 = "https://www.thecocktaildb.com/images/ingredients/" + resultitem.strIngredient2 + "-small.png";
                        resultitem.Imagen3 = "https://www.thecocktaildb.com/images/ingredients/" + resultitem.strIngredient3 + "-small.png";
                        resultitem.Imagen4 = "https://www.thecocktaildb.com/images/ingredients/" + resultitem.strIngredient4 + "-small.png";

                        cocteles.Coctels.Add(resultitem);
                    }
                }
            }
            return View(cocteles);
        }
        [HttpPost]
        public IActionResult GetById(string strDrink)
        {
            ML.drinks drinks = new ML.drinks();
            drinks.Coctels = new List<object>();
            using(var client=new HttpClient())
            {
                client.BaseAddress = new Uri("https://www.thecocktaildb.com/api/");
                var responsetask = client.GetAsync("json/v1/1/search.php?s="+strDrink);
                responsetask.Wait();
                var result = responsetask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readtask = result.Content.ReadAsAsync<dynamic>();
                    readtask.Wait();
                    foreach (dynamic item in readtask.Result.drinks)
                    {
                        ML.drinks resultitem = new ML.drinks();
                        resultitem.idDrink = item.idDrink;
                        resultitem.strDrink = item.strDrink;
                        resultitem.strDrinkThumb = item.strDrinkThumb;
                        resultitem.strInstructions = item.strInstructionsES;
                        resultitem.strCategory = item.strCategory;
                        resultitem.strIngredient1 = item.strIngredient1;
                        resultitem.strIngredient2 = item.strIngredient2;
                        resultitem.strIngredient3 = item.strIngredient3;
                        resultitem.strIngredient4 = item.strIngredient4;
                        resultitem.Imagen1 = "https://www.thecocktaildb.com/images/ingredients/" + resultitem.strIngredient1 + "-small.png";
                        resultitem.Imagen2 = "https://www.thecocktaildb.com/images/ingredients/" + resultitem.strIngredient2 + "-small.png";
                        resultitem.Imagen3 = "https://www.thecocktaildb.com/images/ingredients/" + resultitem.strIngredient3 + "-small.png";
                        resultitem.Imagen4 = "https://www.thecocktaildb.com/images/ingredients/" + resultitem.strIngredient4 + "-small.png";

                        drinks.Coctels.Add(resultitem);
                    }
                }
            }
            return View(drinks);
        }
    }
}

VHernandezCocteleria/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using VHernandezCocteleria.Models;

namespace VHernandezCocteleria.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

VHernandezCocteleria/Views/Cocteles/GetAllNombre.cshtml
@model ML.drinks
@{
    ViewData["Title"] = "GetAllNombre";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="Row">
        <div class="text-center">
          
        </div>
    </div>

</div>

<div class="col-md-12">

    @using (Html.BeginForm("GetById", "Cocteles", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="row text-center">
            <div class="col-md-3">
                @Html.LabelFor(model => model.strDrink)
                @Html.TextBoxFor(model => model.strDrink, new { @class = "form-control", @id = "txtsrtDrink"})
                @Html.Label(null, "",new{@class="lblDrink"})
            </div>
            <div class="col-md-3">
                <input type="submit" value="Buscar" class="btn btn-success" />
            </div>
        </div>
    }
</div>


<hr />

        @foreach (ML.drinks cocteles in Model.Coctels)
        {
         
 
    
    <main>
        <div class="card" style="width: 20rem;">
            <img src="@cocteles.strDrinkThumb" class="card-img-top">
            <div class="card-content">
                <h2>
                    @cocteles.strDrink
                </h2>
                <p>
                    @cocteles.strInstructions
                </p>
                <a href="#" class="button">
                    <img src="@cocteles.Imagen1" style="width: 50px; heigh:50px;">
                   
                    <span class="material-symbols-outlined">
                       
                    </span>
                </a>
            </div>
           
        </div>
    </main>
             
        
        }

VHernandezCocteleria/Views/Cocteles/GetById.cshtml
@model ML.drinks
@{
    ViewData["Title"] = "GetById";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<hr />

<div class="col-md-12">

    @using (Html.BeginForm("GetById", "Cocteles", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="row text-center">
            <div class="col-md-3">
                @Html.LabelFor(model => model.strDrink)
                @Html.TextBoxFor(model => model.strDrink, new { @class = "form-control", @id = "txtsrtDrink"})
                @Html.Label(null, "",new{@class="lblDrink"})
            </div>
            <div class="col-md-3">
                <input type="submit" value="Buscar" class="btn btn-success" />

            </div>
        </div>
    }
</div>

@foreach (ML.drinks cocteles in Model.Coctels)
{
    <div class="card mb-3" style="width: 18rem; display: inline-flex; width:100px height:100px;">
        <img src="@cocteles.strDrinkThumb" class="card-img-top">
        <div class="card-body">
            <h5 class="card-title">@cocteles.strDrink</h5>
            <p class="card-text">@cocteles.strInstructions</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">@cocteles.idDrink</li>
            <li class="list-group-item">@cocteles.strCategory</li>
            <ul class="card-title card-header text-center bg-secondary"><h5>Ingredientes</h5></ul>

            <li class="list-group-item" style="width:50px height:40px;"><img id="Img" src="@cocteles.Imagen1" />@cocteles.strIngredient1</li>
            <li class="list-group-item" style="width:50px height:40px;"><img id="Img" src="@cocteles.Imagen2" />@cocteles.strIngredient2</li>
            <li class="list-group-item" style="width:50px height:40px;"><img id="Img" src="@cocteles.Imagen3" />@cocteles.strIngredient3</li>

        </ul>

    </div>
}

VHernandezCocteleria/Views/Cocteles/Ingredientes.cshtml
@model ML.drinks
@{
    ViewData["Title"] = "Ingredientes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Ingredientes</h1>

VHernandezCocteleria/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

VHernandezCocteleria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VHernandezCocteleria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VHernandezCocteleria.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Estilos.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed&family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VHernandezCocteleria</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cocteles" asp-action="GetAllNombre">Cocteles</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - VHernandezCocteleria - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>